/**
 * Domain types for The Flying Bus.
 * These mirror the database enums and are used throughout the app.
 * database.ts (generated by Supabase) is the source for raw DB types.
 */

export type AgeBand = '8-10' | '11-13' | '14-18'

export type AccountType = 'youth' | 'parent' | 'editor' | 'moderator' | 'admin' | 'sponsor'

export type AccountStatus = 'active' | 'suspended' | 'frozen' | 'deleted' | 'pending_exit'

export type UserRole =
  | 'contributor'
  | 'author'
  | 'junior_editor'
  | 'editor'
  | 'channel_host'
  | 'club_captain'
  | 'moderator'
  | 'admin'
  | 'sponsor'

export type RoleScopeType = 'global' | 'club'

export type SubmissionStatus =
  | 'draft'
  | 'submitted'
  | 'pending_parent_approval'
  | 'rejected_by_parent'
  | 'expired_parent_approval'
  | 'in_review'
  | 'needs_changes'
  | 'approved'
  | 'rejected'
  | 'published'
  | 'flagged_review'

export type ContentType =
  | 'text'
  | 'image'
  | 'debate'
  | 'story_episode'
  | 'world_window_report'

export type ScoreType = 'participation' | 'creator'

export type KanaEventType = 'earned' | 'spent' | 'pending' | 'cancelled'

export type ReviewStatus = 'pending' | 'in_review' | 'approved' | 'rejected' | 'needs_changes'

export type ModerationFlagStatus =
  | 'open'
  | 'under_review'
  | 'resolved'
  | 'dismissed'
  | 'escalated'

export type GuardianLinkStatus = 'pending' | 'active' | 'revoked'

export type CampaignStatus = 'active' | 'funded' | 'closed'

export type MediaModerationStatus = 'pending' | 'clean' | 'flagged' | 'rejected'

export type ChallengeSeasonType = 'weekly' | 'seasonal'

export type ChallengeSeasonStatus = 'draft' | 'active' | 'scoring' | 'closed'

export type ChannelVideoStatus = 'processing' | 'ready' | 'rejected'

export type SponsorCampaignStatus = 'inquiry' | 'active' | 'complete' | 'declined'

export type NotificationType =
  | 'submission_approved'
  | 'submission_rejected'
  | 'submission_needs_changes'
  | 'badge_earned'
  | 'kana_earned'
  | 'challenge_result'
  | 'parent_approval_needed'
  | 'parent_spend_approval_needed'
  | 'moderation_action'
  | 'system_announcement'

/** Safe public profile fields — never includes DOB, age_band, or sensitive data */
export interface PublicProfile {
  username: string
  displayName: string
  avatarUrl: string | null
  creatorLevel: number
  badges: PublicBadge[]
  featuredSubmissions: PublicSubmission[]
  clubs: PublicClubMembership[]
}

export interface PublicBadge {
  slug: string
  name: string
  iconUrl: string
  earnedAt: string
}

export interface PublicSubmission {
  id: string
  title: string
  contentType: ContentType
  publishedAt: string
}

export interface PublicClubMembership {
  clubSlug: string
  clubName: string
}

/** API response shape for the three public WordPress widget endpoints */
export interface PublicChallengeResponse {
  title: string
  prompt: string
  clubName: string
  clubSlug: string
  endsAt: string
  entryCount: number
}

export interface PublicLeaderboardEntry {
  displayName: string
  creatorScore: number
  participationScore: number
  badgeCount: number
  creatorLevel: number
}

export interface PublicImpactResponse {
  title: string
  goalDescription: string
  kanaTarget: number
  kanaCurrent: number
  percentComplete: number
  status: CampaignStatus
}
